### ISSUE TITLE
[Feature request] Offensive prayer tracking

### ISSUE THREAD

**Issue by DasilvaB** [Matsyir/pvp-performance-tracker#11]
Not sure if this correct place to put a future request.

Would it be possible to track if your hits were using correct prayers such as piety or rigor, would be a really nice feature.

**Comment by Matsyir** [comment]
Yes, this is the right place for suggestions.

It's possible for you, the main player, but not the opponent - we can't detect what offensive prayer they're using. So, if we did this and applied it to the deserved damage, it wouldn't be fair to either you or the opponent. Currently, it basically assumes you get all the offensives right - so if we did this, you'd likely be at a slight disadvantage compared to your opponent, or if we adjusted it, your opponent might be at a disadvantage. There's no consistent estimation that will make it fair for both players. So, for deserved damage, not going to happen.

Would you find this useful as its own separate statistic, displayed similarly to off-pray hits, _only available for the main player_? Displayed as like, "12/20 successful offensive prayers". There would be no value for the opponent. I don't think it would be that valuable without the comparison against the opponent, but it could be helpful for improving. It is definitely possible in that style. Let me know what you think.

**Comment by DasilvaB** [comment]
Actually yeah that's exactly what I was picturing. I've been using the tracker, and since I'm not the best at pking I think it would be useful to see how many hits I actually made with the correct prayer. Just another stat to see if I'm doing something incorrect and if it needs to be improved. I do agree that it shouldn't change the expected damage at all.

**Comment by Matsyir** [comment]
Sounds good. Sure why not, definitely can help for improving. From what I've seen, it should be fairly simple to implement. No timeline promises, since I've been decently occupied/lazy, but I do plan to add this with the next update. 👍

**Comment by Matsyir** [comment]
I've implemented this in the most recent commit c5f3b9417d1e5c20844e150b36d3cf96811901db

It's on the overlay (off by default, and note that you can have a max of 5 lines on the overlay), panel, and also in the fight log window. Sorry for the wait!
