### ISSUE TITLE
Installing the plugin causes the invalid fight history popup

### ISSUE THREAD

**Issue by Nightfirecat** [Matsyir/pvp-performance-tracker#13]
Per title, the fight history loading failed comes up when installing the plugin for the first time--the one here: https://github.com/Matsyir/pvp-performance-tracker/blob/7b5ad90dc681db9d4a9aa6b6caa41c1959489f52/src/main/java/matsyir/pvpperformancetracker/PvpPerformanceTrackerPlugin.java#L484

**Comment by Matsyir** [comment]
Oops. Thanks for the heads up. I'll try to get rid of that ASAP, pretty bad first impression. In fact, I'll try to completely replace modals for those "on load" messages, I also noticed some odd behavior on mac when "always on top" is on.
