### ISSUE TITLE
UI update causes lag after ~1k fights logged

### ISSUE THREAD

**Issue by Nightfirecat** [Matsyir/pvp-performance-tracker#20]
**Related plugin component(s)**
Fight Log Panel

**Describe the bug**
When having many fights logged already, recording a new fight causes the full client (game and UI frame) to freeze for a short period of time

**To reproduce**
1. Create many fight entries. (in my case, it happened after roughly 1000)
2. Defeat an opponent or be defeated in LMS, or some other way to have a fight logged

**Expected behavior**
UI updates should not cause any freezing

**Additional context**
This is an issue in the main client as well, for panels such as the loot tracker panel. We've handled it there by limiting the number of items shown as Swing simply becomes sluggish after a certain number of items are being layouted.

**Comment by Matsyir** [comment]
This is a known issue. The best solution I know of for now is to reduce your saved fight limit (it's an option in the config, default to 1k). If you wanted to save your existing fights before reducing your limit/clearing your history then you can export your data to a file until you want to import it again later.

I'm not really sure how to implement the UI for this without pre-loading/creating every component. I've done something similar for Android Studio with a "RecyclerView" and I've looked into it for swing but there doesn't seem to be an equivalent component that does the "recycling" for you, and a custom implementation of one kinda seems like overkill for a project like this - at least for me, with not much Swing experience. It looks like that's what was done for the loot tracker - only having 500 loot tracker boxes loaded at a time? The code for it is kind of going over my head though. I don't think I'm reading it correctly. I understand more or less what has to be done, but I don't know how to do it all in Swing 😐 there's just so much to manage, I have no idea how I would keep the scrollbar working properly while doing that, for one example. I'm not sure how I would know _when_ to load more/remove older entries either. Would love to get this fixed though. But I honestly don't see myself doing it. Is it simpler than I think?

**Comment by Nightfirecat** [comment]
Even without implementing pagination or any kind of "infinite scrolling" or anything like that, you could limit the panel to loading a certain number of the recorded fights. eg. [Limit this to some sane number](https://github.com/Matsyir/pvp-performance-tracker/blob/5996a4b49b453d44e117d9db88c0527e494cbe16/src/main/java/matsyir/pvpperformancetracker/views/FightHistoryTabPanel.java#L63) instead of simply doing `forEach()` to keep from displaying them all.

**Comment by Matsyir** [comment]
Gotcha, I see. I like that, it would allow you to continue adding to your total stats without having to reset stats to fix the lag issue. I think I'll add another config for "Displayed Fight Limit" defaulted to ~500 or so to be used that way. And also increase the default "saved fight limit", since the actual storage is negligible if we're avoiding the excessive UI creation.

**Comment by Matsyir** [comment]
Finally got around to this - sorry for the delay, I haven't been playing lately so unfortunately this hasn't really been in my priorities. Just submitted the PR.
