### ISSUE TITLE
Voidwaker (Korasi) shows as Dragon Warhammer special attack and calculates damage incorrectly

### ISSUE THREAD

**Issue by Hieb** [Matsyir/pvp-performance-tracker#35]
**Related plugin component(s)**
Statistic #2: Deserved Damage, Fight Log Window

**Description**
When using a Voidwaker special attack, it is registered as a DWH spec, calculating against melee pray with crush accuracy, rolling the damage the DWH spec would produce and NOT the guaranteed damage and minimum/maximum of the voidwaker.

**To reproduce**
Attack someone with a Voidwaker special attack while using the plugin and check the fight log for offprayer and expected damage.

**Expected behavior**
Voidwaker spec should show up with correct minimum/maximum hits and 100% accuracy, with protect from magic being the correct prayer to reduce damage.
**Screenshots**
If applicable, add screenshots or clips to help explain your problem.
![image](https://user-images.githubusercontent.com/60852503/226494940-d51f83ff-78e0-4108-90f3-fc6a5222e890.png)
![image](https://user-images.githubusercontent.com/60852503/226494958-8e43788d-189b-4799-9a13-e924c8cac05b.png)

**Comment by Matsyir** [comment]
Interesting, the voidwalker spec was never intentionally tracked (_yet_, simply hasn't been added at all), it just happens to reuse the same animation as dragon warhammer so this happened.

Still should be able to be fixed by also checking for the weapon when this animation occurs (and properly implementing the spec for correct damage values).

**Comment by Hieb** [comment]
If you find the time, please implement such a fix. This weapon is finding use basically all throughout PvP these days, even having been introduced to LMS. It's making the tracker near useless for deserved damage stat in 90% of pvp fights. Thanks for the response

**Comment by Matsyir** [comment]
I should be able to get around to this and a few other small things this Friday. Sorry about the wait, I understand this is affecting a lot of fights currently.

I've been too drained from work to code on my free time at all, but I am finally switching to a 4-day work week which will give me the extra time I need to recover and contribute to projects again.

**Comment by Matsyir** [comment]
Just FYI this has been fixed but it's not live quite yet, it will be there once the update gets approved by main RL devs/reviewers. I'd expect it to be sometime tonight or tomorrow morning but I can't be sure, a lot of plugin hub plugins & updates these days.
